# Faça um programa que leia um número inteiro qualquer.
# Mostre na tela a sua tabuada.
num = int(input('Digite um número para ver sua tabuada: '))
print('-' * 12)
print(f'{num} x {1:2} = {num * 1:2}')
print(f'{num} x {2:2} = {num * 2:2}')
print(f'{num} x {3:2} = {num * 3:2}')
print(f'{num} x {4:2} = {num * 4:2}')
print(f'{num} x {5:2} = {num * 5:2}')
print(f'{num} x {6:2} = {num * 6:2}')
print(f'{num} x {7:2} = {num * 7:2}')
print(f'{num} x {8:2} = {num * 8:2}')
print(f'{num} x {9:2} = {num * 9:2}')
print(f'{num} x {10:2} = {num * 10:2}')
print('-' * 12)